name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  build:
      name: Publish release to PyPI
      env:
        PYPI_USERNAME_STSCI_MAINTAINER: ${{ secrets.PYPI_USERNAME_STSCI_MAINTAINER }}
        PYPI_PASSWORD_STSCI_MAINTAINER: ${{ secrets.PYPI_PASSWORD_STSCI_MAINTAINER }}
        PYPI_TEST: ${{ secrets.PYPI_TEST }}
      runs-on: ubuntu-latest
      steps:

          # Check out the commit containing this workflow file.
          - name: checkout repo
            uses: actions/checkout@v2
         
          - name: custom action
            uses: spacetelescope/action-publish_to_pypi@1.2.0
            id: custom_action_0
